export const MarketFormConfig = {
    TITLE_CREATE: 'Create Market',
    TITLE_EDIT: 'Edit Market',
    MAX_MARKET_CODE_LENGTH: 2,
    MIN_MARKET_CODE_LENGTH: 2,
    MAX_LONG_CODE_LENGTH: 20,
    MIN_LONG_CODE_LENGTH: 7,
    MARKET_CODE_VALIDATION_REGEX: /^[a-zA-Z]+$/,
    MESSAGES:{
    SUCCESS_MESSAGES:{
        
    } ,  
    ERROR_MESSAGES: {
      REQUIRED_MARKET_CODE: 'PAGE.PLACEHOLDERS.ERROR_MARKET_CODE_REQUIRED',
      REQUIRED_MARKET_NAME: 'PAGE.PLACEHOLDERS.ERROR_MARKET_NAME_REQUIRED',
      MARKET_CODE_EXISTS: 'PAGE.PLACEHOLDERS.ERROR_MARKET_CODE_EXISTS',
      MARKET_NAME_EXISTS: 'PAGE.PLACEHOLDERS.ERROR_MARKET_NAME_EXISTS',
    }},
    BUTTONS: {
      UPDATE_MARKET: 'PAGE.BUTTONS.UPDATE_MARKET',
      CREATE_MARKET: 'PAGE.BUTTONS.CREATE_MARKET',
    },
    
  };
  